import type { Metadata } from "next";
import "./null.css";
import "./globals.scss";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import {Welcome} from "@/components/Welcome/Welcome";
import {Services} from "@/components/Services/Services";
import {Contacts} from "@/components/Contacts/Contacts";
import {About} from "@/components/About/About";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body /*className={inter.className}*/>
      <Header/>
      <Welcome/>
      <About/>
      <Services/>
      {children}
      <Contacts/>
      <Footer/>
      </body>
    </html>
  );
}





















